development:
  host: localhost
  adapter: mysql2
  database: monpatois
  username: root  
  password: judith
  

test:
  host: 
  database: 

# set these environment variables on your prod server
production:
  host: localhost
  adapter: mysql2
  database: monpatois
  username: monpatois
  password: monpatois
  